### ISSUE TITLE
Menu clips/hidden if wider than screen

### ISSUE THREAD

**Issue by kimberlyhirsh** [am1t/microdotblog-paper#11]
The navigation menu clips/is hidden if there are too many links in it to fit on a screen. See comparison in images between Desktop and Mobile.
<img width="960" alt="Screenshot 2022-07-06 235517" src="https://user-images.githubusercontent.com/5825002/177687419-852243ba-caf6-4303-bc85-af7324bea656.png" alt="Screenshot of Paper theme on kimberlyhirsh.com on Desktop">
<img width="356" alt="Screenshot 2022-07-06 235629" src="https://user-images.githubusercontent.com/5825002/177687422-723e2269-105c-4a91-bcdb-d21e27673d6c.png" alt="Screenshot of Paper theme on kimberlyhirsh.com on Mobile">

**Comment by am1t** [comment]
I missed this issue, so didn't respond earlier. Anyway, I had recently hidden the menu items on overflow as I wasn't sure what the right behaviour should be. A horizontal scrollbar at the top didn't look good. If needed, you can change this with this custom CSS.

```
.menu {
    overflow:auto
}
```

**Comment by kimberlyhirsh** [comment]
Thanks. I think there must be some kind of media-query way to deal with this. I may play with it later and see what I can figure out. I'll let you know.

**Comment by am1t** [comment]
I have set this to `auto` as part of a recent upgrade. We can create another issue if there's a better way.
