### ISSUE TITLE
Time with date on main page and single posts

### ISSUE THREAD

**Issue by maique** [am1t/microdotblog-paper#12]
Quick question: Is there a way to add a time stamp (24 hours format would be awesome, but 12 will work as well) to the date stamp on the main page and individual post pages?

I've tried going through the code, but am way over my head on this one.

**Comment by am1t** [comment]
That should be possible. I don't want to introduce another configuration though, makes the usage unnecessarily complicated. Let me figure out if there's a simple way.

**Comment by am1t** [comment]
In the meantime though, if possible, you can change `{{ .Date | time.Format ":date_medium" }}` to `{{ .Date | time.Format "Jan 02, 2006 15:04" }}` in `list.html` and `single.html` files. This would put the date in the format as required by you :)

**Comment by maique** [comment]
Thank you so much. That's exactly what I was looking for, no need to add the new setting in the general release.

**Comment by am1t** [comment]
Great, will close the issue then :)
