### ISSUE TITLE
Links in Content

### ISSUE THREAD

**Issue by jupiterking32** [am1t/microdotblog-paper#7]
Hey there, I’m new to Micro.Blog and really love this theme but am having some trouble modifying it for my needs and was wondering if you could help. 

I’m trying to do two things:

1. Show full content in the list view. 
This seems easy. In list.html I added a custom theme and edited { .Summary | truncate 200 } to { .Content}. This worked but if there were any links embedded in the content it’ll appear randomly above the title. 

2. Allow links in content in list view. 
Partially related to issue 1. I’d like to have clickable links within my content in the list view. Right now the entire content is just a link to the post. Any way to get this working?

Thanks!

**Comment by jupiterking32** [comment]
So I fixed my main issues by replacing the content section of “list.html” with the content from “single.html”. Now I’ve got full posts! I also adjusted the perma link so only the date is clickable to link to the individual article.

One last thing that I’m trying to figure out. With all this completed I can’t get links (a href) to display correctly in titles. If I have a link in a title it’ll show up fine on micro.blog account but on this theme is just shows up as html code.

**Comment by am1t** [comment]
I am glad you managed to resolve the issue. For the remaining one around links in the title, can you please share any link?

**Comment by jupiterking32** [comment]
Sure! Here’s a test I just made: https://amick.me/2022/03/26/a-hrefhttpwwwgooglecomtest-title.html

**Comment by am1t** [comment]
I have fixed both the issues with [the latest upgrade](https://www.amitgawande.com/2022/04/29/paper-theme-now.html). Please upgrade your theme and let me know if it works. You can open another issue if you face any issues.
